### ISSUE TITLE
user list for not loged in user fix

### ISSUE THREAD

**Issue by aleksandrenko** [obshtestvo/howto.bg#16]
Да се приложи fixa, за error 500, когато нелогнат потребител се опита да види списъка с регистрирани хора. 
Има го описан във форума на системата.

**Comment by antitoxic** [comment]
Аз намирам: http://meta.osqa.net/questions/2424/500-error-with-users Има ли друго?

**Comment by aleksandrenko** [comment]
май не :), ти ми го беше показал последно, мисля че беше точно това.

**Comment by antitoxic** [comment]
аз ли? вярно :)) че аз не помня ще проверя отново какво пише там. аз до последно мислех че им е някакъв feature това. ще потърся пак

**Comment by antitoxic** [comment]
Намерих проблема. Намерих и решение: http://jira.osqa.net/browse/OSQA-917. Ще pushna днес.
