### ISSUE TITLE
Страницата с индивидуалните профили на потребителите не е достъпна.

### ISSUE THREAD

**Issue by tsikov** [obshtestvo/howto.bg#26]
![screen shot 2014-08-22 at 23 18 28](https://cloud.githubusercontent.com/assets/1625606/4016856/96a59a94-2a39-11e4-8ca3-11fbd42ce019.png)

Ето един пример http://www.howto.bg/users/17/

**Comment by tochev** [comment]
Благодарим, оправено е.
