### ISSUE TITLE
Сините бутони и инпут полетата

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/howto.bg#4]
![screenshot](http://dl.dropbox.com/u/4296335/Selection_011.png) 

![screenshot](http://dl.dropbox.com/u/4296335/Selection_012.png) 

може би ще е хубаво бутоните и input полетата да са на 1 ред, прилепнали и с изравнени височини? не съм сигурен

**Comment by aleksandrenko** [comment]
не съм го изтествал, но мисля че знам от какво е и мисля че е fixнато.
