### ISSUE TITLE
Страницата с badge-овете и някакво тикче

### ISSUE THREAD

**Issue by antitoxic** [obshtestvo/howto.bg#7]
![screenshot](http://dl.dropbox.com/u/4296335/Selection_015.png) 

Страницата с badge-овете, това тикче там е някакъв бъг?

**Comment by aleksandrenko** [comment]
Не е бъг, макар че и аз така реагирах като го видях за първи път. Показва кои от значките вече имаш като регистриран потребител. 

Ще го направя като стил на самата икона, може би със зелена stroke линия.

**Comment by aleksandrenko** [comment]
lokalno go promenih, tova pole, koeto e vinagi otdeleno za tova checkche go nqma 
sega ako znachkata e spechelena se dobavq class na edin ot parent elementite i i taka moje da se stylva razlichno. v momenta ima green border - 1px 

(sorry za shliokavicata)
